/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itshare.system.view.design;

import com.itshare.banksystem.bll.ClientBusinessLogicLayer;
import com.itshare.banksystem.model.entities.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author amero
 */
public class Test extends javax.swing.JFrame {
    private ClientBusinessLogicLayer business = new ClientBusinessLogicLayer();

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstField = new javax.swing.JTextField();
        lastField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        selectBtn = new javax.swing.JButton();
        ClientBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(firstField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 490, 70));

        lastField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lastField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 490, 70));

        ageField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 490, 70));

        idField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 490, 70));

        selectBtn.setBackground(new java.awt.Color(0, 0, 51));
        selectBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        selectBtn.setForeground(new java.awt.Color(255, 153, 0));
        selectBtn.setText("Select");
        selectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectBtnMouseClicked(evt);
            }
        });
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        jPanel1.add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 140, 50));

        ClientBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/itshare/system/view/resources/clientForm.png"))); // NOI18N
        jPanel1.add(ClientBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1210, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void selectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectBtnMouseClicked

    }//GEN-LAST:event_selectBtnMouseClicked

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed

        try {

            int id = Integer.parseInt(idField.getText());

            Client client = new Client();
            client.setId(id);

            System.out.println(client.toString());

            Client clientData = business.selectClient(client);
            System.out.println(clientData.toString());

            if(clientData !=null){
                firstField.setText(clientData.getFirstname());
                lastField.setText(clientData.getLastname());
                ageField.setText("" + clientData.getAge());
            }
        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "You must Enter an Id", "Error Exception", JOptionPane.ERROR_MESSAGE);
            firstField.setText("");
            lastField.setText("");
            ageField.setText("");

        }
    }//GEN-LAST:event_selectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientBackground;
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField firstField;
    private javax.swing.JTextField idField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastField;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
